### ISSUE TITLE
Improve description of Mixin Content exercise

### ISSUE THREAD

**Issue by ManuCastrillonM** [workshopper/learn-sass#52]
Hi, I think that are a mistake in the mixin-content sample

The sample says:
```sass
 @mixin apply-to-ie6-only {  
       * html {  
         @content;  
       }  
     }  
     @include apply-to-ie6-only {  
       #logo {  
         background-image: url(/logo.gif);  
       }  
     }  
```
and the correct use of the mixin would be:
```sass
 @mixin apply-to-ie6-only {
  * html {
    @content;
  }
}

#logo {
  @include apply-to-ie6-only {
    background-image: url("/logo.gif");
  }
}
```

**Comment by claudiopro** [comment]
Hi Manuela, thanks for spotting this and taking the time to report it!

Most of these snippets were copied over verbatim from the `sass/sass` repo behind the http://sass-lang.com/ website and are clearly out of date 😄   This particular snippet was taken from [the SASS_REFERENCE.md file at revision 747185238f](https://github.com/sass/sass/blob/747185238fdb4c09bfe8da8cdd3c3da3c276c8db/doc-src/SASS_REFERENCE.md).

Would you feel comfortable preparing a PR updating the samples yourself?

**Comment by ManuCastrillonM** [comment]
I was reviewing and the example is correct, the problem is that it is not illustrative with the activity that is proposed to do later, I will prepare a PR with a more appropriate example for this

**Comment by claudiopro** [comment]
Super, thank you!

**Comment by ManuCastrillonM** [comment]
I need authorization to do the PR

**Comment by ManuCastrillonM** [comment]
Ready! resolve #53

**Comment by claudiopro** [comment]
May I ask you to update the issue and commit message to better clarify the intent, e.g. "Improve description of Mixin Content exercise"? This way it will be clear what the change does when looking at the repo history. Thank you!

**Comment by ManuCastrillonM** [comment]
Sure! #54

**Comment by ManuCastrillonM** [comment]
Hi ! Please check the PR #63
